name: "CI: Main Workflow"
run-name: ${{ github.actor }} CI Workflow

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "**.ts"
  push:
    branches: ["*"]
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Installation
        run: npm install

      - name: Run single command
        run: npm run lint

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Run Installation
        run: npm install

      - name: Run Installation
        run: npm install -g react-scripts

      - name: Run single command
        run: npm test
